#!/bin/sh
# *******************************************************************
# delbin
# 	delete temporary working files
#
# Copyright (C) Aleksandr Bocharov
# Author: Aleksandr Bocharov
# Date: 24.09.2024
# *******************************************************************

cd  src/comp/
rm -f  *.asm 
rm -f  *.o 
rm -f  *.log

