#!/bin/sh 
#*******************************************************************
# r2clg_dbg
#	compile from refal to GNU-assembler + link + go
# 	arg: $1 - name of refal programm (without ext ref)
#	result: running of $1.exe 
#
# Copyright(C) Aleksandr Bocharov
# Author : Aleksandr Bocharov
# Date : 05.08.2024
# *******************************************************************

bin/refal2 $1 > $1.log
as -o $1.o $1.asm >> $1.log
gcc -o $1 lib/mainrf.o $1.o -Wl,-L./lib -Wl,-lr2_dbg >> $1.log
$1
