#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-06-09
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabdclg
# compile from refal to object file + debugger link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1.exe debugger
# *******************************************************************

bin/refalabc $1 -l,"-o $1.o -Wno-override-module" > $1.log
clang -o $1 $1.o lib/obj/refalab_debugger.o -Llib -lrefalab >> $1.log
$1
