#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabdclg_dbg
# compile from refal to object file + debugger link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1.exe debugger in debugging mode 
# *******************************************************************

bin/refalabc $1 -a,"-o $1.o" > $1.log
clang -o $1 $1.o lib/obj/rfdbg.o -Llib -lrefalab_dbg >> $1.log
$1
