#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-06-09
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabdclg_dbg
# compile from refal to object file + debugger link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1_dbg.exe debugger in debugging mode 
# *******************************************************************

bin/refalabc $1 -l,"-o $1_dbg.o -O0 -g -Wno-override-module" > $1_dbg.log
clang -o $1_dbg $1_dbg.o lib/obj/refalab_debugger_dbg.o -Llib -lrefalab_dbg >> $1_dbg.log
$1_dbg
