#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-03-10
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# RefalABc
# compile from refal to GNU-assembler 
# arg: $1 - name of refal programm (without extension ref)
# result: $1.s in GNU assembler language 
# *******************************************************************

bin/RefalAB $1 > $1.log
