#!/bin/sh 

# Copyright 2024 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-11-23
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# RefalABclg
# compile from refal to GNU-assembler + link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1.exe 
# *******************************************************************

bin/RefalAB $1 > $1.log
as -o $1.o $1.asm >> $1.log
clang -o $1 $1.o lib/mainrf.o -Llib -lRefalAB >> $1.log
$1
