#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-31
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabclg_dbg
# compile from refal to object file + link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1.exe in debugging mode 
# *******************************************************************

bin/refalabc $1 -a,"-o $1.o" > $1.log
clang -o $1 $1.o lib/obj/mainrf_dbg.o -Llib -lrefalab_dbg >> $1.log
$1
