#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-06-09
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabco_dbg
# compile from refal to object file in debugging mode
# arg: $1 - name of refal programm (without extension ref)
# result: $1_dbg.o
# *******************************************************************

bin/refalabc $1 -l,"-o $1_dbg.o -O0 -g -Wno-override-module" > $1_dbg.log
