#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-14
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# RefalABclg_dbg
# compile from refal to object file + link + go
# arg: $1 - name of refal programm (without ext ref)
# result: running of $1.exe in debugging mode 
# *******************************************************************

bin/RefalAB $1 -a,"-o $1.o" > $1.log
clang -o $1 $1.o lib/obj/mainrf.o -Llib -lRefalAB_dbg >> $1.log
$1
