#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-14
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabc
# compile from refal to object file
# arg: $1 - name of refal programm (without extension ref)
# result: $1.o
# *******************************************************************

bin/RefalABc $1 -a,"-o $1.o" > $1.log
