#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refalabc
# compile from refal to object file
# arg: $1 - name of refal programm (without extension ref)
# result: $1.o
# *******************************************************************

bin/refalabc $1 -a,"-o $1.o" > $1.log
