#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-10-11
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# set_config
# set environments variables for make RefalAB
# *******************************************************************

# export REFALABMCOMP=gcc
export REFALABMCOMP=clang
