#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# set_env
# set environments variables for RefalAB
# *******************************************************************

export REFALABBIN=$PWD/bin
export REFALABLIB=$PWD/lib
export REFALABINCLUDE=$PWD/include
export REFALABCFLAGS="-pipe -Wall -O2"
