#!/bin/sh

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-05
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# copy_obj
# copy mainrf.o and rfdbg.o
# *******************************************************************

cp ./src/inter/mainrf.o ./lib/obj
cp ./src/inter/rfdbg.o ./lib/obj


