#!/bin/sh

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# copy_obj
# copy mainrf.o and rfdbg.o
# *******************************************************************

cp ./src/inter/mainrf.o ./lib/obj
cp ./src/inter/rfdbg.o ./lib/obj


