#!/bin/sh

# Copyright 2024 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-11-23
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# delbin
# delete temporary working files
# *******************************************************************


cd src/inter/
rm -f  *.asm 
rm -f  *.o 
rm -f  *.log
rm -f  *.lst


