#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-03-10
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# refext
# special script
# compile xext.ref from refal to GNU-assembler + assembling 
# result: xext.o  
# *******************************************************************

bin/RefalAB src/inter/xext > src/inter/xext.log
as -o src/inter/xext.o src/inter/xext.s >> src/inter/xext.log 
