#!/bin/sh 

# Copyright 2024 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-11-23
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# refplatform
# special script
# compile xplatformposix.ref from refal to GNU-assembler + assembling
# result: xplatform.o  
# *******************************************************************

bin/RefalAB src/inter/xplatformposix > src/inter/xplatform.log
as -o src/inter/xplatform.o src/inter/xplatformposix.asm >> src/inter/xplatform.log 
