#!/bin/sh 

# Copyright 2024 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2024-09-30
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# refplatform
# 	special script
#	compile platformposix.ref from refal to GNU-assembler + assembling. 
#	result: platform.o  
# *******************************************************************

bin/RefalAB src/inter/platformposix > src/inter/platform.log
as -o src/inter/platform.o src/inter/platformposix.asm >> src/inter/platform.log 
