#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxplatformposix
# special script
# compile xplatformposix.ref from refal to object file
# result: xplatform.o  
# *******************************************************************

bin/refalabc src/inter/xplatformposix -a,"-o src/inter/xplatform.o" > src/inter/xplatform.log
