#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxhof
# special script
# compile xhof.ref from refal to object file
# result: xhof.o  
# *******************************************************************

bin/refalabc src/inter/xhof -a,"-o src/inter/xhof.o" > src/inter/xhof.log