#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-31
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxcomp2
# special script
# compile xcomp2.ref from refal to object file
# result: xcomp2.o  
# *******************************************************************

bin/refalabc src/inter/xcomp2 -a,"-o src/inter/xcomp2.o" > src/inter/xcomp2.log