#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxext
# special script
# compile xext.ref from refal to object file
# result: xext.o  
# *******************************************************************

bin/refalabc src/inter/xext -a,"-o src/inter/xext.o" > src/inter/xext.log
