#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxar2
# special script
# compile xar2.ref from refal to object file
# result: xar2.o  
# *******************************************************************

bin/refalabc src/inter/xar2 -a,"-o src/inter/xar2.o" > src/inter/xar2.log