#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxfio2
# special script
# compile xfio2.ref from refal to object file
# result: xfio2.o  
# *******************************************************************

bin/refalabc src/inter/xfio2 -a,"-o src/inter/xfio2.o" > src/inter/xfio2.log
