#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxcomp2
# special script
# compile xcomp2.ref from refal to object file
# result: xcomp2.o  
# *******************************************************************

bin/refalabc src/inter/xcomp2 -a,"-o src/inter/xcomp2.o" > src/inter/xcomp2.log