#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxbool
# special script
# compile xbool.ref from refal to object file
# result: xbool.o  
# *******************************************************************

bin/refalabc src/inter/xbool -a,"-o src/inter/xbool.o" > src/inter/xbool.log
