#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxsys2
# special script
# compile xsys2.ref from refal to object file
# result: xsys2.o  
# *******************************************************************

bin/refalabc src/inter/xsys2 -a,"-o src/inter/xsys2.o" > src/inter/xsys2.log
