#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-14
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# refxcv
# special script
# compile xcv.ref from refal to object file
# result: xcv.o  
# *******************************************************************

bin/RefalABc src/inter/xcv -a,"-o src/inter/xcv.o" > src/inter/xcv.log
