#!/bin/sh 

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxmo2
# special script
# compile xmo2.ref from refal to object file
# result: xmo2.o  
# *******************************************************************

bin/refalabc src/inter/xmo2 -a,"-o src/inter/xmo2.o" > src/inter/xmo2.log
