#!/bin/sh 

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-10-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# refxhof
# special script
# compile xhof.ref from refal to object file
# result: xhof.o  
# *******************************************************************

bin/refalabc src/inter/xhof -a,"-o src/inter/xhof.o" > src/inter/xhof.log