#!/bin/sh

# Copyright 2025 Aleksandr Bocharov
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
# 2025-03-10
# https://github.com/Aleksandr3Bocharov/RefalAB

# *******************************************************************
# delbin
# delete temporary working files
# *******************************************************************

cd  src/comp/
rm -f  *.s
rm -f  *.o
rm -f  *.log
