#!/bin/sh

# Copyright (c) 2026 Aleksandr Bocharov
# SPDX-License-Identifier: MIT
# 2026-05-29
# https://github.com/Aleksandr3Bocharov/refalab

# *******************************************************************
# delbin
# delete temporary working files
# *******************************************************************

cd  src/comp/
rm -f  *.s
rm -f  *.o
rm -f  *.log
